#pragma once

#include "../../include/config.hpp"

#undef PIPCORE_PLATFORM
#define PIPCORE_PLATFORM DESKTOP

#undef PIPCORE_DISPLAY
#define PIPCORE_DISPLAY SIMULATOR

#undef PIPCORE_ENABLE_PREFS
#define PIPCORE_ENABLE_PREFS 1

#undef PIPCORE_ENABLE_WIFI
#define PIPCORE_ENABLE_WIFI 1

#undef PIPCORE_ENABLE_OTA
#define PIPCORE_ENABLE_OTA 1

#undef PIPGUI_WIFI
#define PIPGUI_WIFI 0

#undef PIPGUI_OTA
#define PIPGUI_OTA 0

#undef PIPGUI_SCREENSHOTS
#define PIPGUI_SCREENSHOTS 0

#undef PIPGUI_SCREENSHOT_MODE
#define PIPGUI_SCREENSHOT_MODE 0

#ifdef PIPGUI_DEBUG_DISPLAY_SERIAL
#undef PIPGUI_DEBUG_DISPLAY_SERIAL
#endif
#define PIPGUI_DEBUG_DISPLAY_SERIAL 0

#ifndef PIPGUI_SIM_SCALE
#define PIPGUI_SIM_SCALE 1
#endif

#ifndef PIPGUI_SIM_BTN_PREV_PIN
#define PIPGUI_SIM_BTN_PREV_PIN 4
#endif

#ifndef PIPGUI_SIM_BTN_NEXT_PIN
#define PIPGUI_SIM_BTN_NEXT_PIN 20
#endif

#ifndef PIPGUI_SIM_BTN_SELECT_PIN
#define PIPGUI_SIM_BTN_SELECT_PIN 21
#endif
