#pragma once

#include "../../include/config.hpp"

#undef PIPCORE_PLATFORM
#define PIPCORE_PLATFORM DESKTOP

#undef PIPCORE_DISPLAY
#define PIPCORE_DISPLAY SIMULATOR

#undef PIPCORE_ENABLE_PREFS
#define PIPCORE_ENABLE_PREFS 1

#undef PIPCORE_ENABLE_WIFI
#define PIPCORE_ENABLE_WIFI 1

#undef PIPCORE_ENABLE_OTA
#define PIPCORE_ENABLE_OTA 1
